export const vinVehicleResponseObject = {
  ABS: "",
  ActiveSafetySysNote: "",
  AdaptiveCruiseControl: "",
  AdaptiveDrivingBeam: "",
  AdaptiveHeadlights: "",
  AdditionalErrorText: "",
  AirBagLocCurtain: "",
  AirBagLocFront: "",
  AirBagLocKnee: "",
  AirBagLocSeatCushion: "",
  AirBagLocSide: "",
  AutoReverseSystem: "",
  AutomaticPedestrianAlertingSound: "",
  AxleConfiguration: "",
  Axles: "",
  BasePrice: "",
  BatteryA: "",
  BatteryA_to: "",
  BatteryCells: "",
  BatteryInfo: "",
  BatteryKWh: "",
  BatteryKWh_to: "",
  BatteryModules: "",
  BatteryPacks: "",
  BatteryType: "",
  BatteryV: "",
  BatteryV_to: "",
  BedLengthIN: "",
  BedType: "",
  BlindSpotIntervention: "",
  BlindSpotMon: "",
  BodyCabType: "MDHD: Conventional",
  BodyClass: "Truck-Tractor",
  BrakeSystemDesc: "",
  BrakeSystemType: "Air and Hydraulic",
  BusFloorConfigType: "Not Applicable",
  BusLength: "",
  BusType: "Not Applicable",
  CAN_AACN: "",
  CIB: "",
  CashForClunkers: "",
  ChargerLevel: "",
  ChargerPowerKW: "",
  CoolingType: "",
  CurbWeightLB: "",
  CustomMotorcycleType: "Not Applicable",
  DaytimeRunningLight: "",
  DestinationMarket: "",
  DisplacementCC: "14800.0",
  DisplacementCI: "903.15141260203",
  DisplacementL: "14.8",
  Doors: "",
  DriveType: "6x4",
  DriverAssist: "",
  DynamicBrakeSupport: "",
  EDR: "",
  ESC: "",
  EVDriveUnit: "",
  ElectrificationLevel: "",
  EngineConfiguration: "In-Line",
  EngineCycles: "",
  EngineCylinders: "6",
  EngineHP: "",
  EngineHP_to: "",
  EngineKW: "",
  EngineManufacturer: "",
  EngineModel: "Detroit Diesel DD15",
  EntertainmentSystem: "",
  ErrorCode: "0",
  ErrorText: "0 - VIN decoded clean. Check Digit (9th position) is correct",
  ForwardCollisionWarning: "",
  FuelInjectionType: "",
  FuelTypePrimary: "Diesel",
  FuelTypeSecondary: "",
  GCWR: "",
  GCWR_to: "",
  GVWR: "Class 8: 33,001 lb and above (14,969 kg and above)",
  GVWR_to: "",
  KeylessIgnition: "",
  LaneCenteringAssistance: "",
  LaneDepartureWarning: "",
  LaneKeepSystem: "",
  LowerBeamHeadlampLightSource: "",
  Make: "FREIGHTLINER",
  MakeID: "450",
  Manufacturer: "DAIMLER TRUCKS NORTH AMERICA LLC",
  ManufacturerId: "1024",
  Model: "Cascadia",
  ModelID: "2501",
  ModelYear: "2019",
  MotorcycleChassisType: "Not Applicable",
  MotorcycleSuspensionType: "Not Applicable",
  NCSABodyType: "",
  NCSAMake: "",
  NCSAMapExcApprovedBy: "",
  NCSAMapExcApprovedOn: "",
  NCSAMappingException: "",
  NCSAModel: "",
  NCSANote: "",
  NonLandUse: "",
  Note: "",
  OtherBusInfo: "",
  OtherEngineInfo: "",
  OtherMotorcycleInfo: "",
  OtherRestraintSystemInfo: "",
  OtherTrailerInfo: "",
  ParkAssist: "",
  PedestrianAutomaticEmergencyBraking: "",
  PlantCity: "SALTILLO",
  PlantCompanyName: "",
  PlantCountry: "MEXICO",
  PlantState: "COAHUILA",
  PossibleValues: "",
  Pretensioner: "",
  RearAutomaticEmergencyBraking: "",
  RearCrossTrafficAlert: "",
  RearVisibilitySystem: "",
  SAEAutomationLevel: "",
  SAEAutomationLevel_to: "",
  SeatBeltsAll: "",
  SeatRows: "",
  Seats: "",
  SemiautomaticHeadlampBeamSwitching: "",
  Series: "",
  Series2: "",
  SteeringLocation: "",
  SuggestedVIN: "",
  TPMS: "",
  TopSpeedMPH: "",
  TrackWidth: "",
  TractionControl: "",
  TrailerBodyType: "Not Applicable",
  TrailerLength: "",
  TrailerType: "Not Applicable",
  TransmissionSpeeds: "",
  TransmissionStyle: "",
  Trim: '126" sleeper cab',
  Trim2: "",
  Turbo: "",
  VIN: "3AKJHHDR3KSKX6689",
  ValveTrainDesign: "",
  VehicleDescriptor: "3AKJHHDR*KS",
  VehicleType: "TRUCK ",
  WheelBaseLong: "",
  WheelBaseShort: "",
  WheelBaseType: "",
  WheelSizeFront: "",
  WheelSizeRear: "",
  Wheels: "",
  Windows: "",
};
